[project]
name = "python-function"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aws-lambda-powertools>=3.4.1",
    "aws-xray-sdk>=2.14.0",
    "boto3>=1.36.6",
    "fastjsonschema>=2.21.1",
]
