# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class SSTDemoApi:
        type: str
        url: str
    class SSTDemoDB:
        name: str
        type: str

